#ifndef BITMASKSHEADER_H
#define BITMASKSHEADER_H

// USE POWER OF 2 
#define PLAYER_BITMASK 1 
#define ENEMY_BITMASK 2
#define NEUTRAL_BITMASK 4
#define WALLS_BITMASK 8
#define PRESSURE_PLATE 16
#define PLAYER_PROJECTILE_BITMASK 2048

enum PHYSICS_TAG
{
    PHYSICS_TAG_PLAYER,
    PHYSICS_TAG_ENEMY,

    PHYSICS_TAG_WALL,
    PHYSICS_TAG_INTERACTABLE,

    NUM_TAGS
};

#endif